version: '3.4'

services:
  chitapi:
    image: ${DOCKER_REGISTRY-}chitapi
    build:
      context: .
      dockerfile: ChitAPI/Dockerfile
      
    ports:
     -   8085:80
     -   8087:443 
    
    depends_on:
      - sqlserverchitservice
  sqlserverchitservice:  
    image: mcr.microsoft.com/mssql/server 
    hostname: 'sqlserverinventoryservice'  
    environment:  
      ACCEPT_EULA: 'Y' 
      SA_PASSWORD: "Vignesh@95"  
    volumes:  
      - ./chitapi:/var/opt/mssql/data  
    ports:  
      - '1406:1433'  
    expose:  
      - 1433 
 